# Заказы в фастфуде Chipotle

### Шаг 1. Импортируем библиотеки.

In [204]:
import pandas as pd

### Шаг 2. Читаем датасет в переменную chipo

In [205]:
# tsv файл - это tab separated values, чтобы корректно его загрузить, укажи аргумент sep='\t'
path = 'https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv'

chipo = pd.read_csv(path, sep = '\t')
chipo

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98
...,...,...,...,...,...
4617,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Sour ...",$11.75
4618,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",$11.75
4619,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$11.25
4620,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",$8.75
4621,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$8.75

### Шаг 3. Смотрим первые 10 записей

In [206]:
chipo.head(10)

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98
5,3,1,Chicken Bowl,"[Fresh Tomato Salsa (Mild), [Rice, Cheese, Sou...",$10.98
6,3,1,Side of Chips,NaN,$1.69
7,4,1,Steak Burrito,"[Tomatillo Red Chili Salsa, [Fajita Vegetables...",$11.75
8,4,1,Steak Soft Tacos,"[Tomatillo Green Chili Salsa, [Pinto Beans, Ch...",$9.25
9,5,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Pinto...",$9.25

### Шаг 4. Сколько всего записей в датасете?

In [207]:
# Решение 1
chipo.shape[0]

4622

In [208]:
# Решение 2
len(chipo)

4622

### Шаг 5. Сколько всего колонок в датасете?

In [209]:
chipo.shape[1]

5

### Шаг 6. Выведите имена всех колонок

In [210]:
chipo.columns

Index(['order_id', 'quantity', 'item_name', 'choice_description',
       'item_price'],
      dtype='object')

### Шаг 7. Как проиндексирован датасет? Выведи индекс датасета

In [211]:
chipo.index

RangeIndex(start=0, stop=4622, step=1)

### Шаг 8. Какое блюдо заказывали больше всего?

In [212]:
popular_name = chipo['item_name'].value_counts().index[0]
popular_name

'Chicken Bowl'

### Шаг 9. Сколько раз заказывали самое популярное блюдо?

In [213]:
chipo[chipo['item_name'] == popular_name]['quantity'].sum()

761

### Шаг 10. Какое блюдо в колонке choice_description заказывали больше всего?

In [214]:
chipo['choice_description']\
    .apply(lambda x: x.replace('[', '').replace(']', '').split(', ') if x == x else x)\
    .explode().value_counts().index[0]

'Rice'

### Шаг 11. Сколько суммарно блюд было заказано?

In [215]:
chipo['quantity'].sum()

4972

### Шаг 12. Измени тип колонки `price` в `float`

In [218]:
chipo['item_price'] = chipo['item_price'].apply(lambda x: x.replace('$', '')).astype(float)
chipo.dtypes

order_id                int64
quantity                int64
item_name              object
choice_description     object
item_price            float64
dtype: object

### Шаг 13. Сколько денег суммарно было получено?

In [235]:
revenue = chipo['item_price'].sum()
revenue

34500.16

### Шаг 14. Сколько заказов суммарно было сделано?

In [238]:
number_orders = chipo['order_id'].nunique()
number_orders

1834

### Шаг 15. Какая средняя цена заказа?

In [237]:
# Решение 1
round(revenue/number_orders, 2)

18.81

In [242]:
# Решение 2
chipo.groupby('order_id').sum().mean()['item_price']

18.811428571428568

### Шаг 16. Сколько _разных_ блюд было продано?

In [243]:
chipo['item_name'].nunique()

50