# Заказы в фастфуде Chipotle

### Шаг 1. Импортируем библиотеки.

In [1]:
import pandas as pd

### Шаг 2. Прочитаем датасет в переменную chipo

In [2]:
path = 'https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv'
# уже знаете откуда взять данные?)

In [3]:
chipo = pd.read_csv(path, sep='\t')
chipo

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98
...,...,...,...,...,...
4617,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Sour ...",$11.75
4618,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",$11.75
4619,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$11.25
4620,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",$8.75
4621,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$8.75

### Шаг 3. Сколько блюд стоят больше $10.00?

In [4]:
chipo['item_name'][chipo['item_price'].apply(lambda x: float(x.replace('$', ''))) > 10].nunique()

31

### Шаг 4. Сколько стоит каждое блюдо?
###### выведите датафрейм с колонками item_name и item_price

In [5]:
chipo[['item_name', 'item_price']].drop_duplicates()

                                  item_name item_price
0              Chips and Fresh Tomato Salsa     $2.39
1                                      Izze     $3.39
2                          Nantucket Nectar     $3.39
3     Chips and Tomatillo-Green Chili Salsa     $2.39
4                              Chicken Bowl    $16.98
...                                     ...        ...
4237                    Chips and Guacamole     $8.50
4354                       Steak Soft Tacos    $18.50
4489                    Chips and Guacamole    $17.80
4509                                  Chips     $1.99
4510                          Barbacoa Bowl    $11.49

[209 rows x 2 columns]

### Шаг 5. Сортируем по названию блюда

In [6]:
chipo.sort_values(by = 'item_name')

,order_id,quantity,item_name,choice_description,item_price
3389,1360,2,6 Pack Soft Drink,[Diet Coke],$12.98
341,148,1,6 Pack Soft Drink,[Diet Coke],$6.49
1849,749,1,6 Pack Soft Drink,[Coke],$6.49
1860,754,1,6 Pack Soft Drink,[Diet Coke],$6.49
2713,1076,1,6 Pack Soft Drink,[Coke],$6.49
...,...,...,...,...,...
2384,948,1,Veggie Soft Tacos,"[Roasted Chili Corn Salsa, [Fajita Vegetables,...",$8.75
781,322,1,Veggie Soft Tacos,"[Fresh Tomato Salsa, [Black Beans, Cheese, Sou...",$8.75
2851,1132,1,Veggie Soft Tacos,"[Roasted Chili Corn Salsa (Medium), [Black Bea...",$8.49
1699,688,1,Veggie Soft Tacos,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",$11.25
1395,567,1,Veggie Soft Tacos,"[Fresh Tomato Salsa (Mild), [Pinto Beans, Rice...",$8.49

### Шаг 6. Сколько раз заказывали самое дорогое блюдо?

In [7]:
chipo[chipo['item_price'].apply(lambda x: float(x.replace('$', ''))) \
    == chipo['item_price'].apply(lambda x: float(x.replace('$', ''))).max()]\
        .shape[0]

1

### Шаг 7. Сколько раз заказывали Veggie Salad Bowl?

In [8]:
chipo[chipo['item_name'] == 'Veggie Salad Bowl']['order_id'].nunique()

18

### Шаг 8. В скольких заказах присутствует больше одной Canned Soda?

In [33]:
#Количество подряд заказанных напитков за один раз
(chipo[['order_id', 'quantity', 'item_name']][chipo['item_name'] == 'Canned Soda']\
    .groupby('order_id').agg({'quantity': 'sum'})> 1).sum()

quantity    24
dtype: int64