# Имена детей в США

https://www.kaggle.com/kaggle/us-baby-names
либо забираем датасет из папки datasets/US_Baby_Names_right.csv

### Шаг 1. Импортируем библиотеки.

In [1]:
import pandas as pd

### Шаг 2. Нужный файл уже лежит в папке data

In [8]:
# download file from https://www.kaggle.com/ukveteran/us-baby-names-right
path = '../../../../datasets/US_Baby_Names_right.csv'

### Шаг 3. Записываем его в переменную baby_names

In [9]:
baby_names = pd.read_csv(path)
baby_names

         Unnamed: 0       Id     Name  Year Gender State  Count
0             11349    11350     Emma  2004      F    AK     62
1             11350    11351  Madison  2004      F    AK     48
2             11351    11352   Hannah  2004      F    AK     46
3             11352    11353    Grace  2004      F    AK     44
4             11353    11354    Emily  2004      F    AK     41
...             ...      ...      ...   ...    ...   ...    ...
1016390     5647421  5647422     Seth  2014      M    WY      5
1016391     5647422  5647423  Spencer  2014      M    WY      5
1016392     5647423  5647424     Tyce  2014      M    WY      5
1016393     5647424  5647425   Victor  2014      M    WY      5
1016394     5647425  5647426   Waylon  2014      M    WY      5

[1016395 rows x 7 columns]

### Шаг 4. Смотрим первые 10 записей

In [10]:
baby_names.head(10)

   Unnamed: 0     Id      Name  Year Gender State  Count
0       11349  11350      Emma  2004      F    AK     62
1       11350  11351   Madison  2004      F    AK     48
2       11351  11352    Hannah  2004      F    AK     46
3       11352  11353     Grace  2004      F    AK     44
4       11353  11354     Emily  2004      F    AK     41
5       11354  11355   Abigail  2004      F    AK     37
6       11355  11356    Olivia  2004      F    AK     33
7       11356  11357  Isabella  2004      F    AK     30
8       11357  11358    Alyssa  2004      F    AK     29
9       11358  11359    Sophia  2004      F    AK     28

### Шаг 5. Удаляем колонки 'Unnamed: 0' и 'Id'

In [20]:
baby_names.drop(columns=['Unnamed: 0', 'Id'], inplace=True)

### Шаг 6. В датасете больше мужских или женских имен?

In [29]:
baby_names['Gender'].value_counts().index[0]

'F'

### Шаг 7. Посчитайте, сколько раз встречалось каждое имя и запишите получившийся датафрейм в переменную names

In [34]:
names = baby_names['Name'].value_counts()
names

Riley      1112
Avery      1080
Jordan     1073
Peyton     1064
Hayden     1049
           ...
Terryn        1
Yanna         1
Zemirah       1
Emmilyn       1
Coalton       1
Name: Name, Length: 17632, dtype: int64

### Шаг 8. Сколько разных имен в датасете?

In [60]:
names.shape[0]

17632

### Шаг 9. Какое самое частое имя?

In [37]:
names.index[0]

'Riley'

### Шаг 10. Сколько разных имен встречаются реже всего?

In [57]:
names[names == 1].count()

3682

### Шаг 11. Какое медианное значение количества детей с одинаковым именем?

In [62]:
names[names > 1].median()

14.0

### Шаг 12. Какое среднеквадратичное отклонение количества детей с одинаковым именем?

In [63]:
names[names > 1].std()

133.23489933882885

### Шаг 13. Сделайте саммари с mean, min, max, std и квартилями.

In [66]:
baby_names.describe().round(2)

             Year       Count
count  1016395.00  1016395.00
mean      2009.05       34.85
std          3.14       97.40
min       2004.00        5.00
25%       2006.00        7.00
50%       2009.00       11.00
75%       2012.00       26.00
max       2014.00     4167.00